### ISSUE TITLE
[Proposal] Add more contribution guidelines regarding code readability and annotating arguments.

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#12]
For example, codes should be easy to read and self-explanatory, function arguments should be annotated(see: [EmmyLua annotations](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations)).

Also I feel like some of the existing guidelines can be improved but I have no clue how so.

**Comment by Ocawesome101** [comment]
might do this. thanks for the suggestion.
