### ISSUE TITLE
Executable file loading shenanigans

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#18]
First off, the recognizer sometimes get a blank string instead of the actual first 128 chars of the file. This seem to occur on big files.
```lua
--!lua
local function syscall(call, ...)
    return coroutine.yield("syscall", call, ...)
end

local function open(path, mode, ...)
    return syscall("open", path, mode, ...)
end

local function read(fd, ...)
    return syscall("read", fd, ...)
end

local function write(fd, ...)
    return syscall("write", fd, ...)
end

local function close(fd)
    return syscall("close", fd)
end

```

Result from `printk(k.L_DEBUG, "%s(%s)", type(header), tostring(header))`:
![Screenshot-2022-02-15,15-38-11](https://user-images.githubusercontent.com/25323231/154024139-b02832de-50f5-457e-be71-fff7fdad6b04.png)

In case of small files, the header is valid but the loader fails to read the file instead(first dump is from recognizer, second is from the loader:
![Screenshot-2022-02-15,15-39-35](https://user-images.githubusercontent.com/25323231/154024516-9de541d5-a9dc-47d5-9789-ee65fa78acd2.png)

**Comment by Ocawesome101** [comment]
This seems like an issue with the buffer library - I will look into it.

**Comment by Ocawesome101** [comment]
this was indeed a buffering issue - specifically, seeking was broken. there were a few other bugs as well.
