### ISSUE TITLE
`chdir` and `getcwd` syscall

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#19]
Just a todo for myself. Will go sleep after this.

**Comment by Ocawesome101** [comment]
this should be a pair - `chdir` and `getcwd`

**Comment by atirutw** [comment]
> `getcwd`

A libc call but ok, because I don't know what `getcwd` calls internally.

**Comment by atirutw** [comment]
Update: turns out the Linux kernel actually provides `getcwd()` as a syscall.

> On Linux, the kernel provides a getcwd() system call, which the  functions described in this page will use if possible.
