### ISSUE TITLE
Improving the now-CYX format specifications

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#2]
I'm not well-versed in terms of binary file format, so take this with a grain of salt. This topic may also need further discussions.

- As of currently, the CYX format have no method of specifying the format's version. This could pose a problem because if we make changes to the format, it would be extremely compatibility breaking. I propose that a byte containing a version number be put somewhere around the header area along with the flags and OS ID so that CYX loaders can do something about different format versions instead of dying trying to load CYX files with newer format.
- You can only either static link or dynamic link all libraries used. While this is not a big problem, I can see some developer wanting to selectively static-link libraries for various reasons.
- The specification on static & dynamic linking is a bit vague, such as the requirement of linking an interpreter, etc.

As a side note, I think writing the docs in Markdown instead of plain text is also a good idea

**Comment by Ocawesome101** [comment]
Regarding linking, I'm not sure even GCC's linker supports doing what you suggest (though you can dynamically reference a statically linked library, for sure).

The other things you suggest seem pretty reasonable.
