### ISSUE TITLE
`kill` syscall

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#20]
Can also be used to check if a process is running by using signal 0 which does not actually kill the process, but returns an error if it doesn't exist.

**Comment by atirutw** [comment]
I feel like this could be a low priority for now. Will implement this when needed ig.

**Comment by Ocawesome101** [comment]
yeah, this requires a bit more infrastructure than just a system call. as-is there's no signal handling capability whatsoever.
