### ISSUE TITLE
Calling `stat` on root causes an error

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#23]
Example:
![Screenshot-2022-02-16,15-12-51](https://user-images.githubusercontent.com/25323231/154223289-d9f1d5e5-6a46-4444-9d0e-1ec73be19d20.png)

This prevents me from implementing a dir existent check for `chdir`.

**Comment by atirutw** [comment]
Look's like either `is_attribute()` in `fs/managed.lua` or `k.split_path()` in `fs/main.lua` is the cause of this. I am inclined to think the fault is with `k.split_path()`, though. Calling `opendir` on root also causes the error. Who knows how many FS operations are affected.

**Comment by Ocawesome101** [comment]
This is indeed the fault of `is_attribute()`, which assumes there will always be a final path segment. 'tis an oversight on my part.
