### ISSUE TITLE
proper flushing of buffers and whatnot at shutdown

### ISSUE THREAD

**Issue by Ocawesome101** [oc-ulos/oc-cynosure-2#26]
this isn't super important for now, but particularly once we get into unmanaged filesystems and caching we need a way for drivers to register things to do when the computer is shut down.  unmounting filesystems at shutdown is a good first step.

- [x] shutdown hooks
- [x] flush buffers on shutdown (more important)
- [x] unmount filesystems on shutdown (slightly less important for now)

**Comment by atirutw** [comment]
A proposal for an entire architecture for the hook system:
- Hooks are event-based e.g. `k.register_hook("key_down", func)`
- A function `k.process_hooks()` that go and run all hook functions according to the last pulled event or an override string and arguments.
- `k.process_hooks("shutdown")` when shutting down

Refactoring the codes to use this new system should be relatively easy and it would allow more things for both the kernel itself and, in the near or far future, kernel modules.

**Comment by Ocawesome101** [comment]
making the whole signal handling system generic in the form of a hook system is something i quite like - and it's an excellent solution that doesn't require much refactoring - though it needs some protection to make sure userspace can't e.g. call the `"shutdown"` hook with `computer.pushSignal("shutdown")`.
