### ISSUE TITLE
Proper ANSI color codes support

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#28]
Cynosure 2's TTY driver seem to either have a bug with ANSI colors or doesn't support all of them.

## Test codes
Color loop:
```lua
for fg=30,37 do
  for bg=40,47 do
    -- Using `\27` does not seem to make any difference here
    printf("\x1b[%d;%dm%d;%d\x1b[0m ", fg, bg, fg, bg)
  end
  printf("\n")
end
```

Cynosure 2 `printf`:
```lua
local function printf(fmt, ...)
  coroutine.yield("syscall", "write", 1, string.format(fmt, ...))
end
```

Lua `printf`:
```lua
local function printf(fmt, ...) io.write(string.format(fmt, ...)) end
```

## Results
GNOME Terminal
![Screenshot-2022-03-07,08-26-50](https://user-images.githubusercontent.com/25323231/156952609-5890513d-b802-4ab5-9186-0c78b369a1e9.png)

VSCode
![Screenshot-2022-03-07,08-27-07](https://user-images.githubusercontent.com/25323231/156952633-1d18cb31-29b4-4d8b-87cd-f32beeb3348f.png)

Cynosure 2(T2)
![Screenshot-2022-03-07,08-27-25](https://user-images.githubusercontent.com/25323231/156952658-e2a81480-0830-4294-b609-bc8833251012.png)

Cynosure 2(T3)
![Screenshot-2022-03-07,08-45-45](https://user-images.githubusercontent.com/25323231/156953951-cc721a3a-00c1-4968-8b51-d5e766dc4dc4.png)

**Comment by Ocawesome101** [comment]
this is indeed a bug. i'm not sure exactly what's causing it but i'll look into it.

**Comment by atirutw** [comment]
I forgot to use T3 screen for this. Looks like it only have problem with setting background color.

**Comment by Ocawesome101** [comment]
aha. i'll fix the background color issue and make it set the palette colors on T2 so it looks right.

**Comment by atirutw** [comment]
I'll implement the background color SGR then

**Comment by atirutw** [comment]
The BG color is not even implemented, it seems

**Comment by Ocawesome101** [comment]
nah bg color is implemented, just wasn't working (was setting foreground rather than background)
