### ISSUE TITLE
Weird TTY color bug with scrolling

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#29]
ANSI color changes seem to become weird after the screen scrolls. Running the codes found in #28 can trigger this bug.

What happened:
![Screenshot-2022-03-07,11-12-59](https://user-images.githubusercontent.com/25323231/156966789-5a903238-3648-4668-8bf3-e5e5971da9b7.png)

What should have happened:
![Screenshot-2022-03-07,11-14-34](https://user-images.githubusercontent.com/25323231/156966915-fbb46cf4-c27c-4e09-9299-4916eeeca235.png)

**Comment by Ocawesome101** [comment]
well, part (possibly all) of the issue is that `\27[0m` wasn't implemented.

**Comment by Ocawesome101** [comment]
update: can confirm that was indeed the issue - see below for what it looks like now vs konsole
![Screenshot_20220307_002128](https://user-images.githubusercontent.com/50844998/156972808-e548a4cb-c26b-4655-ab8e-56697bcc3639.png)
.
