### ISSUE TITLE
Errors in forked processeds are not handled

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#32]

**Comment by Ocawesome101** [comment]
Can you clarify the expected behavior?

**Comment by atirutw** [comment]
I expected all Lua executables loaded would have their errors reported. Looks like my codes in ec51b1e2e50a015e008719231f33159c97d602b0 have something wrong with it to only report *some* Lua errors. No idea what went wrong though.

**Comment by atirutw** [comment]
I just realized this is before only errors from program loaded with `execve` are handled. Closed.
