### ISSUE TITLE
Dirent without name when listing files in the component FS

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#34]
Loop:
```lua
repeat
  local dirent = coroutine.yield("syscall", "readdir", dirfd)
  if dirent then
    coroutine.yield("syscall", "write", 1, (dirent.name) .. "\n")
  end
until not dirent
```

Result:
![Screenshot-2022-03-13,03-39-54](https://user-images.githubusercontent.com/25323231/158034261-0a5f11be-91ba-4501-aed9-81b77f23d2c1.png)

If I null check the dirent name, the loop will run infinitely. I'm guessing `fs/component.lua`'s `opendir()` rteturns a bad dirfd.

**Comment by Ocawesome101** [comment]
This is due to the provider's `:readdir` method not properly nil checking.
