### ISSUE TITLE
[TODO] Fix potential bug in `k.fd_from_rwf()`

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#6]
Context: https://github.com/Ocawesome101/oc-cynosure-2/blob/a347842b9c864b77676fad8d9e42227d02d20eae/src/filedesc.lua#L72-L75

I will work on this myself later but I'm quite in a rush right now.

**Comment by Ocawesome101** [comment]
Can you elaborate on what t you believe the bug to be?

**Comment by atirutw** [comment]
When you call A Lua function using a colon (`foo:bar() `) the first
argument the function gets is `foo` hence why "OOP" functions get
unexpected argument when you call them without the colon. AFAIK if you
don't name the first argument "self" then you have to replace "self" with
the name of the first argument.

**Comment by Ocawesome101** [comment]
Whoops, you’re right. Good catch.  thanks!

**Comment by Ocawesome101** [comment]
I had somehow completely missed that.

**Comment by atirutw** [comment]
Lol it's okay. I've made a lot of dumb mistakes too.

**Comment by Ocawesome101** [comment]
Issue fixed. Closing.
