### ISSUE TITLE
Potential TTY bug in `internalwrite()`

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#9]
https://github.com/Ocawesome101/oc-cynosure-2/blob/268b4f75830edac3d102f2e582856e1ae81c2dbc/src/tty.lua#L407-L412

I don't see any definition for `str` and I don't know what it's supposed to be either. This one is probably for you, @Ocawesome101

**Comment by atirutw** [comment]
Also in the same file: https://github.com/Ocawesome101/oc-cynosure-2/blob/268b4f75830edac3d102f2e582856e1ae81c2dbc/src/tty.lua#L482-L487

**Comment by Ocawesome101** [comment]
yeah those are both errors.  thanks for pointing those out.
